server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Diese Zeile leitet alles an React weiter
        try_files $uri $uri/ /index.html; 
    }
}