GET http://localhost:5000/api/database
Content-Type: application/json

# {
#     "username": "Janek2",
#     "password": "123",
#     "password2" : "23 4",
#     "public_key": "str",
#     "encrypted_private_key": "str"
# }
